version: '2'

services:
  express-node-qa:
    build:
      context: ../../
      dockerfile: ./Docker/Dockerfile-node
    ports:
      - "3000:3000"
    networks:
      - causefresh_net_qa

  causefresh-db-qa:
    build:
      context: ../../
      dockerfile: ./Docker/Dockerfile-mysql
    restart: always
    networks:
      causefresh_net_qa:
            aliases:
              - ${dbHost}
    ports:
      - "3306:3306"

networks:
    causefresh_net_qa:
      driver: bridge

